### ISSUE TITLE
angular.module is not a function after updating to 0.2.4

### ISSUE THREAD

**Issue by Sharykhin** [grevory/angular-local-storage#290]
After updating till the version 0.2.4 I got the following error:
angular.module is not a function
I use browserify, here is how it looks in my file
`require('angularjs');
require('angular-local-storage');  
// other code`

The error occurs only on version 0.2.4, if I fix version to 0.2.3 everything works properly.
Actually I install you library via bower.

**Comment by ealves-pt** [comment]
Issue occurs for the same reason as #288 and #289. I will revert this changes and soon.

**Comment by ealves-pt** [comment]
This should be fixed with PR #291. I will wait for some feedback to see if it's possible to close this issue.

**Comment by stefanmaric** [comment]
I got the same issue upgrading to 0.2.4. Should 0.2.5 fix it?

**Comment by ealves-pt** [comment]
I suppose that after 0.2.5 this problem will disappear.

**Comment by stefanmaric** [comment]
> I suppose that after 0.2.5 this problem will disappear.

Confirmed. Thanks!
